/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Inicial;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class principal {
    
    System.out.println("Hello World!");
    System.out.println("Meu segundo comando");
    
    }

