/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package dia1;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        System.out.println("Digite um número:");
        float x = leitor.nextFloat();
        System.out.println("Digite outro número:");
        float y = leitor.nextFloat();
        float a = x+y;
        float b = x-y;
        float c = x*y;
        float d = x/y;
        
        System.out.println("Soma: " + a);
        System.out.println("Subtracao: " + b);
        System.out.println("Multiplicaco: " + c);
        System.out.println("Divisao: " + d);
        
        
        
        
        
                
    
    }
}
